all:
	gcc -Wall -Werror -g -pthread -I/usr/local/include/gstreamer-0.10 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libxml2 -L/usr/local/lib -lgstreamer-0.10 -lgstaudio-0.10 -lgobject-2.0 -lgmodule-2.0 -ldl -lgthread-2.0 -lrt -lxml2 -lglib-2.0 multiChannel.c -o multiChannel 
