#!/bin/bash

LIMIT=8
APPNAME=gst-launch-0.10

for ((i=0, j=1; i < LIMIT ; i++, j++))
do 
    SRC=${APPNAME}:out_jackaudiosink0_${j}
    DEST=jmeters:in-${j}
    echo connecting port ${SRC} to ${DEST}
    jack_connect ${SRC} ${DEST}
done
