#!/bin/bash

LIMIT=6

for ((i=0, j=1; i < LIMIT ; i++, j++))
do 
    SRC=gst-launch-0.10:out_jackaudiosink${i}_1
    DEST=system:playback_${j}
    echo connecting port ${SRC} to ${DEST}
    jack_connect gst-launch-0.10:out_jackaudiosink${i}_1 system:playback_${j}
done
