all:
	c++ pyInterpreter_main.cpp pyInterpreter.cpp ../hello/hello.o -I /usr/include/python2.5 -I /usr/include/boost/python/ /usr/lib/libboost_python-gcc42-1_34_1.a  /usr/lib/libpython2.5.so.1.0 -o python_main

clean:
	rm embed

