#!/usr/bin/env python

# (c) Simon Piette <simonp@sat.qc.ca>
# GPLv2 or later
# This script will start mivilled in the background, and will start firefox to
# the miville address and port afterward.

import os
import sys
from time import sleep

try:
    user_bin_path = os.environ['PATH'].split(os.pathsep)
except:
    sys.stderr.write('Unable to work with PATH environnement variable')
    sys.exit(1)

 
user_bin_path.insert(0, os.curdir + os.sep + os.path.curdir)

miville_bin = ''
for p in user_bin_path: 
    _miville_bin = os.path.join(p, 'mivilled')
    if os.path.isfile(_miville_bin):
        # oct(5) is r-x permission for any user
        if ( oct(os.stat(_miville_bin).st_mode & 5 ) == oct(5) ):
            miville_bin = _miville_bin

if ( miville_bin == ''):
    sys.stderr.write('No mivilled executable found')
    sys.exit(1)

pid = os.fork()
if (pid == 0):
    # child
    sleep(2)
    os.execl("/usr/bin/firefox", "firefox", "http://localhost:8080")
else:
    # parent
    os.execl(miville_bin, "mivilled")

