#!/bin/bash

if [ $# = 0 ];
then
    PREFIX=/usr/local/
fi
if [ $# = 1 ];
then
    PREFIX=$1/
fi
if [ $# = 2 ];
then
    PREFIX=$1
    DESTDIR=$2
fi

echo "PREFIX: " $PREFIX
echo "DESTDIR: " $DESTDIR

if [ -d py ];
then
    for ext in py txt xml css js png jpg;
    do 
        find py/miville -type f -name \*.$ext -exec install -D {} ${DESTDIR}${PREFIX}{} \;
    done
    find py -name Makefile -exec install -D {} $DESTDIR$PREFIX{} \;
    find py/docs -name \*.txt -exec install -D {} $DESTDIR$PREFIX{} \;
    #install -D "py/docs/Makefile" "$DESTDIR${PREFIX}py/docs/Makefile"
    #install -D "bin/miville.py" "$DESTDIR${PREFIX}bin/miville.py"
fi
