#!/bin/bash

if [ ! -f configure.ac ];
then
    exit 1
fi
if [ -f configure ]
then 
    if [ -f config.log ]
    then
        make distclean 
    else
        ./configure
        make distclean
    fi
fi
autoreconf -fiv && ./configure && make && fakeroot make distcheck 
