#!/bin/bash

if [ ! -f configure.ac ];
then
    exit 1
fi
if [ -f configure ]
then
    if [ ! -f config.log ]
    then
        ./configure
    fi
    make distclean
fi
autoreconf -iv && ./configure && make && fakeroot make distcheck
