#!/bin/bash
mkdir -p html/fig
cp -r fig/*.{png,jpg} html/fig
for doc in installation-manual user-manual
do
    mkdir -p html/$doc
    cd html/$doc
    gnome-doc-tool html -o $doc.html ../../$doc.xml
    sed -i 's!src="fig/!src="../fig/!' *.html
    ln -sf $doc.html index.html
    cd -
done

