v1.0
['dictionary', 
	[
		['unicode', 'Charlotte'], 
		['addressbook.Contact', 
			['dictionary', 
				['kind', 'ip'], 
				['auto_created', 
					['boolean', 'false']], 
				['name', 
					['unicode', 'Charlotte']], 
				['state', 0], 
				['auto_answer', 
					['boolean', 'true']], 
				['connector', 'basic'], 
				['setting', 0], 
				['address', '127.0.0.1'], 
				['port', 2223]]]], 
	['_selected', 
		['unicode', 'Charlotte']], 
	[
		['unicode', 'brrr_vid'], 
		['addressbook.Contact', 
			['dictionary', 
				['kind', 'ip'], 
				['auto_created', 
					['boolean', 'false']], 
				['name', 
					['unicode', 'brrr_vid']], 
				['state', 0], 
				['auto_answer', 
					['boolean', 'true']], 
				['connector', 'basic'], 
				['setting', 10000], 
				['address', '10.10.10.65'], 
				['port', 2222]]]], 
	[
		['unicode', 'Pierre'], 
		['addressbook.Contact', 
			['dictionary', 
				['kind', 'ip'], 
				['auto_created', 
					['boolean', 'false']], 
				['name', 
					['unicode', 'Pierre']], 
				['state', 0], 
				['auto_answer', 
					['boolean', 'true']], 
				['connector', 'basic'], 
				['setting', 0], 
				['address', '127.0.0.1'], 
				['port', 2222]]]], 
	[
		['unicode', 'tzing'], 
		['addressbook.Contact', 
			['dictionary', 
				['kind', 'ip'], 
				['auto_created', 
					['boolean', 'false']], 
				['name', 
					['unicode', 'tzing']], 
				['state', 0], 
				['auto_answer', 
					['boolean', 'true']], 
				['connector', 'basic'], 
				['setting', 0], 
				['address', '10.10.10.66'], 
				['port', 
					['None']]]]]]